---
abstract: 'complete jQuery port to Perl'
author:
  - 'Mamod A. Mehyar <mamod.mehyar@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: jQuery
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Entities: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  XML::LibXML: 0
version: 0.004
